A tutorial of Numpy

# 1 Arrays 
## 1.1 Create Arrays

In [1]:
import numpy as np
# from python list
a = np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])
a[0] = 5
print(a)

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [3]:
# create 2-dimensional array
b = np.array([[1,2,3], [4,5,6]])
print(b)
print(b.shape)
print(b[0,0],b[1,:],b[:,1])

[[1 2 3]
 [4 5 6]]
(2, 3)
1 [4 5 6] [2 5]


In [7]:
# from others method
a = np.zeros((2,2))
print('a:', a)
b = np.ones((3,1))
print('b:', b)
c = np.full((2,2), 7)
print('c:', c)
d = np.eye(2)
print('d:', d)
e = np.random.random((2,2))
print('e:', e)

a: [[ 0.  0.]
 [ 0.  0.]]
b: [[ 1.]
 [ 1.]
 [ 1.]]
c: [[ 7.  7.]
 [ 7.  7.]]
d: [[ 1.  0.]
 [ 0.  1.]]
e: [[ 0.42498497  0.64819431]
 [ 0.54289753  0.81944948]]


/Users/gaufung/anaconda/lib/python3.6/site-packages/numpy/core/numeric.py:301: FutureWarning: in the future, full((2, 2), 7) will return an array of dtype('int64')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


# 1.2 Visit Elements

In [9]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
b = a[:2,1:3]
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


In [10]:
# a slice of array is view of the same data. so modify
# it will modify the original array
print(a[0,1])
b[0,0]=77
print(a[0,1])

2
77


In [11]:
# slice will generate the low rank array 
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
row_r1 = a[1, :]
row_r2 = a[1:2,:]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [12]:
# integer will create subset of array
a = np.array([[1,2], [3, 4], [5, 6]])
print(a[[0,1,2],[0,1,0]])

[1 4 5]


In [13]:
print(np.array([a[0,0],a[1,1],a[2,0]]))

[1 4 5]


In [14]:
print(a[[0,0],[1,1]])

[2 2]


In [15]:
# change every row's elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)
b =  np.array([0,2,0,1])
print(a[np.arange(4),b])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]


In [17]:
a[np.arange(4), b] +=10
print(a)

[[21  2  3]
 [ 4  5 26]
 [27  8  9]
 [10 31 12]]


In [19]:
# Using boolean data
a = np.array([[1,2], [3, 4], [5, 6]])
bool_idx = (a>2)
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [20]:
print(a[bool_idx])
print(a[a>2])

[3 4 5 6]
[3 4 5 6]


In [24]:
print(a[a%3==0])

[3 6]


# 2 Operations

In [25]:
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[5,6], [7,8]], dtype=np.float64)
print(x+y)

[[  6.   8.]
 [ 10.  12.]]


In [26]:
print(np.add(x,y))

[[  6.   8.]
 [ 10.  12.]]


In [27]:
print(x-y)

[[-4. -4.]
 [-4. -4.]]


In [28]:
print(x*y)

[[  5.  12.]
 [ 21.  32.]]


In [29]:
print(x/y)

[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]


In [30]:
print(np.dot(x,y))

[[ 19.  22.]
 [ 43.  50.]]


In [31]:
# sum 
print(np.sum(x))

10.0


In [33]:
print(x)
# compute the each column
print(np.sum(x, axis=0))
# compute the each row
print(np.sum(x, axis=1))

[[ 1.  2.]
 [ 3.  4.]]
[ 4.  6.]
[ 3.  7.]


# 3 Broadcasting
we can do mathematical arrays' operations between different shape size.

In [34]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
#create an empty with the same shape as x
y = np.empty_like(x)
for i in range(4):
    y[i,:]=x[i,:]+v

In [35]:
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [36]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print(vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [37]:
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [39]:
y=x+vv
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [40]:
# broadcasting will help us reduce code
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
print(x+v)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


**Rules** of broadcast
+ 如果数组的秩不同，使用1来将秩较小的数组进行扩展，直到两个数组的尺寸的长度都一样。
+ 如果两个数组在某个维度上的长度是一样的，或者其中一个数组在该维度上长度为1，那么我们就说这两个数组在该维度上是相容的。
+ 如果两个数组在所有维度上都是相容的，他们就能使用广播。
+ 如果两个输入数组的尺寸不同，那么注意其中较大的那个尺寸。因为广播之后，两个数组的尺寸将和那个较大的尺寸一样。
+ 在任何一个维度上，如果一个数组的长度为1，另一个数组长度大于1，那么在该维度上，就好像是对第一个数组进行了复制。